# Generated by Django 3.2 on 2022-09-23 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_author_user'),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentstatus',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.author'),
        ),
    ]
